# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "ehci_pci" "ahci" "megaraid_sas" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/358beab3-354b-4ea5-9699-021ec18b87e5";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/359D-9473";
    fsType = "vfat";
  };

  fileSystems."/tank" = {
    device = "tank";
    fsType = "zfs";
  };

  fileSystems."/tank/backups" = {
    device = "tank/backups";
    fsType = "zfs";
  };

  fileSystems."/tank/media" = {
    device = "tank/media";
    fsType = "zfs";
  };

  fileSystems."/tank/media/movies" = {
    device = "tank/media/movies";
    fsType = "zfs";
  };

  fileSystems."/tank/media/music" = {
    device = "tank/media/music";
    fsType = "zfs";
  };

  fileSystems."/tank/media/tv" = {
    device = "tank/media/tv";
    fsType = "zfs";
  };

  fileSystems."/tank/media/downloads" = {
    device = "tank/media/downloads";
    fsType = "zfs";
  };

  fileSystems."/tank/media/books" = {
    device = "tank/media/books";
    fsType = "zfs";
  };

  fileSystems."/tank/media/pictures" = {
    device = "tank/media/pictures";
    fsType = "zfs";
  };

  fileSystems."/tank/db" = {
    device = "tank/db";
    fsType = "zfs";
  };

  fileSystems."/tank/git" = {
    device = "tank/git";
    fsType = "zfs";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/c3980b41-68c9-4158-8d51-ecb5c5c583b3"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp65s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp65s0f1.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
