# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules = [
      "uhci_hcd"
      "ehci_pci"
      "ahci"
      "xhci_pci"
      "sata_sil24"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "tank/nixos";
      fsType = "zfs";
    };

    "/nix" = {
      device = "tank/nixos/nix";
      fsType = "zfs";
    };

    "/etc" = {
      device = "tank/nixos/etc";
      fsType = "zfs";
    };

    "/var" = {
      device = "tank/nixos/var";
      fsType = "zfs";
    };

    "/var/lib" = {
      device = "tank/nixos/var/lib";
      fsType = "zfs";
    };

    "/var/log" = {
      device = "tank/nixos/var/log";
      fsType = "zfs";
    };

    "/var/spool" = {
      device = "tank/nixos/var/spool";
      fsType = "zfs";
    };

    "/home" = {
      device = "tank/userdata/home";
      fsType = "zfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/5851-DEF2";
      fsType = "vfat";
    };
  };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
